<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class MenuBuilderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $admin_menus = array(
            array(
                "id" => 1,
                "name" => "main_menu",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 2,
                "name" => "footer_menu_one",
                "created_at" => "2025-02-28 06:42:38",
                "updated_at" => "2025-02-28 06:42:38",
            ),
            array(
                "id" => 3,
                "name" => "footer_menu_two",
                "created_at" => "2025-02-28 06:43:25",
                "updated_at" => "2025-02-28 06:43:25",
            ),
            array(
                "id" => 4,
                "name" => "footer_menu_three",
                "created_at" => "2025-02-28 06:43:46",
                "updated_at" => "2025-02-28 06:43:46",
            ),
        );

        $admin_menu_items = array(
            array(
                "id" => 1,
                "label" => "Home",
                "link" => "/",
                "parent_id" => 0,
                "sort" => 0,
                "class" => NULL,
                "menu_id" => 2,
                "depth" => 0,
                "created_at" => "2025-02-28 06:47:31",
                "updated_at" => "2025-02-28 06:47:57",
            ),
            array(
                "id" => 2,
                "label" => "About",
                "link" => "/about",
                "parent_id" => 0,
                "sort" => 1,
                "class" => NULL,
                "menu_id" => 2,
                "depth" => 0,
                "created_at" => "2025-02-28 06:47:57",
                "updated_at" => "2025-02-28 06:49:34",
            ),
            array(
                "id" => 3,
                "label" => "Contact",
                "link" => "/contact",
                "parent_id" => 0,
                "sort" => 2,
                "class" => NULL,
                "menu_id" => 2,
                "depth" => 0,
                "created_at" => "2025-02-28 06:49:33",
                "updated_at" => "2025-02-28 06:49:53",
            ),
            array(
                "id" => 4,
                "label" => "Our Services",
                "link" => "#",
                "parent_id" => 0,
                "sort" => 3,
                "class" => NULL,
                "menu_id" => 2,
                "depth" => 0,
                "created_at" => "2025-02-28 06:49:53",
                "updated_at" => "2025-02-28 06:50:13",
            ),
            array(
                "id" => 5,
                "label" => "More About Us",
                "link" => "#",
                "parent_id" => 0,
                "sort" => 4,
                "class" => NULL,
                "menu_id" => 2,
                "depth" => 0,
                "created_at" => "2025-02-28 06:50:14",
                "updated_at" => "2025-02-28 06:50:14",
            ),
            array(
                "id" => 6,
                "label" => "Terms & Condition",
                "link" => "/terms-and-conditions",
                "parent_id" => 0,
                "sort" => 2,
                "class" => NULL,
                "menu_id" => 3,
                "depth" => 0,
                "created_at" => "2025-02-28 06:59:53",
                "updated_at" => "2025-02-28 07:03:08",
            ),
            array(
                "id" => 7,
                "label" => "Privacy Policy",
                "link" => "/privacy-policy",
                "parent_id" => 0,
                "sort" => 3,
                "class" => NULL,
                "menu_id" => 3,
                "depth" => 0,
                "created_at" => "2025-02-28 07:00:18",
                "updated_at" => "2025-02-28 07:03:08",
            ),
            array(
                "id" => 8,
                "label" => "More About Us",
                "link" => "#",
                "parent_id" => 0,
                "sort" => 4,
                "class" => NULL,
                "menu_id" => 3,
                "depth" => 0,
                "created_at" => "2025-02-28 07:01:51",
                "updated_at" => "2025-02-28 07:03:08",
            ),
            array(
                "id" => 9,
                "label" => "Blogs",
                "link" => "/blogs",
                "parent_id" => 0,
                "sort" => 0,
                "class" => NULL,
                "menu_id" => 3,
                "depth" => 0,
                "created_at" => "2025-02-28 07:02:11",
                "updated_at" => "2025-02-28 07:03:05",
            ),
            array(
                "id" => 10,
                "label" => "Chefs",
                "link" => "/chef",
                "parent_id" => 0,
                "sort" => 1,
                "class" => NULL,
                "menu_id" => 3,
                "depth" => 0,
                "created_at" => "2025-02-28 07:02:53",
                "updated_at" => "2025-02-28 07:03:08",
            ),
            array(
                "id" => 11,
                "label" => "Contact",
                "link" => "/contact",
                "parent_id" => 0,
                "sort" => 0,
                "class" => NULL,
                "menu_id" => 4,
                "depth" => 0,
                "created_at" => "2025-02-28 07:05:04",
                "updated_at" => "2025-02-28 07:05:17",
            ),
            array(
                "id" => 12,
                "label" => "About",
                "link" => "/about",
                "parent_id" => 0,
                "sort" => 2,
                "class" => NULL,
                "menu_id" => 4,
                "depth" => 0,
                "created_at" => "2025-02-28 07:05:17",
                "updated_at" => "2025-02-28 07:05:17",
            ),
            array(
                "id" => 13,
                "label" => "Home",
                "link" => "/",
                "parent_id" => 0,
                "sort" => 0,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2025-02-28 07:08:31",
                "updated_at" => "2025-02-28 07:08:52",
            ),
            array(
                "id" => 14,
                "label" => "About",
                "link" => "/about",
                "parent_id" => 0,
                "sort" => 1,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2025-02-28 07:08:52",
                "updated_at" => "2025-02-28 07:09:21",
            ),
            array(
                "id" => 15,
                "label" => "Chef",
                "link" => "/chef",
                "parent_id" => 21,
                "sort" => 5,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 1,
                "created_at" => "2025-02-28 07:09:21",
                "updated_at" => "2025-02-28 07:15:48",
            ),
            array(
                "id" => 16,
                "label" => "Blogs",
                "link" => "/blogs",
                "parent_id" => 0,
                "sort" => 2,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2025-02-28 07:09:48",
                "updated_at" => "2025-02-28 07:15:39",
            ),
            array(
                "id" => 17,
                "label" => "Contact",
                "link" => "/contact",
                "parent_id" => 0,
                "sort" => 3,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2025-02-28 07:10:13",
                "updated_at" => "2025-02-28 07:15:39",
            ),
            array(
                "id" => 18,
                "label" => "Testimonial",
                "link" => "/testimonial",
                "parent_id" => 21,
                "sort" => 6,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 1,
                "created_at" => "2025-02-28 07:11:11",
                "updated_at" => "2025-02-28 07:15:48",
            ),
            array(
                "id" => 19,
                "label" => "Terms & Condition",
                "link" => "/terms-and-conditions",
                "parent_id" => 21,
                "sort" => 7,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 1,
                "created_at" => "2025-02-28 07:11:41",
                "updated_at" => "2025-02-28 07:15:48",
            ),
            array(
                "id" => 20,
                "label" => "Privacy Policy",
                "link" => "/privacy-policy",
                "parent_id" => 21,
                "sort" => 8,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 1,
                "created_at" => "2025-02-28 07:12:00",
                "updated_at" => "2025-02-28 07:16:02",
            ),
            array(
                "id" => 21,
                "label" => "Pages",
                "link" => "#",
                "parent_id" => 0,
                "sort" => 4,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2025-02-28 07:15:11",
                "updated_at" => "2025-02-28 07:15:48",
            ),
        );

        DB::table('admin_menus')->insert($admin_menus);
        DB::table('admin_menu_items')->insert($admin_menu_items);

    }
}
